### ISSUE TITLE
Issue with Lz4DecoderStream

### ISSUE THREAD

**Issue by Trasiva** [pdjonov/Lz4Stream#1]
I'm uploading lz4 compressed files to our server, and when I am attempting to read them the stream has a very monstrous buffer that is not even remotely close to the size of the uncompressed file. We're on .NET 3.5, using C# for the code, so I had to tweak the Lz4DecoderStream.cs in order to have it work none of which should have affected the overall performance of the file, as all I changed was the generic vars to the appropriate variable type, and removed the optional setting for the inputs from long.maxlength, to requiring a size. 

When I'm checking to detect if the lz4 file is appropriate, I do the following:

``` C#
try
{
        byte[] buffer = new byte[13];
        //Gather the header information.
        //Set the stream to the point of where the data starts, always the same with the way the compression is done.
        int intRead = st.Read(buffer, 0, 13);
        //Check if we have the magic number. Currently the value (in little endian) is 0x184D2204
        if (buffer[3] == 0x18 && buffer[2] == 0x4D && buffer[1] == 0x22 && buffer[0] == 0x04)
        {
                //Use an input length of 14000 for testing purposes. Test files don't exceed this size.
                using (Lz4.Lz4DecoderStream lzStream = new Lz4.Lz4DecoderStream(st, 14000))
                {
                        DownloadCapture(szFileName, szConfig, dtFile, szZip, szExt, szDownload, bSort, lzStream, output);
                }
        }

}
```

 The stream st is a memorystream of the data pulled from the database. Instead of the expected 14000 size buffer, I'm obtaining a 65664 sized buffer, where the first 65535 values are zero, before it actually starts at the position that the memorystream was left at intentionally. Interestingly, it starts right after the number set within the initialization of the DecBufMask value, but I'm having a difficult time following the Lz4DecoderStream code.

**Comment by pdjonov** [comment]
Hi,

That buffer's size has nothing to do with either the input or output file size, the number comes from the Lz4 specification itself. Lz4DecoderStream is specifically written to be reusable because of that buffer, which can obviously put a fair bit of allocation pressure on certain systems.

Note that you can decode smaller files using _much_ less memory if you don't require streaming reads. If you can buffer the whole input stream and create a buffer for the entire output data, then run the decoder directly from the source to the destination. Note that you'd need to grab a different port of Lz4 to .NET for this case as Lz4DecoderStream is written _strictly_ for the case where streaming decompression is necessary.

**Comment by Trasiva** [comment]
Right, I understand that the specification for Lz4 calls for a cyclical buffer, but that doesn't explain why when I pass my memorystream off to the Lz4DecoderStream, that my items are all the way are at the bottom, and I only receive the first 128 bytes. There should be 12742 bytes (the uncompressed file size), no?

**Comment by pdjonov** [comment]
So, I'm confused. What exactly does `DownloadCapture` do with the `Lz4DecoderStream`? What does it mean for your items to be a the "bottom"? The bottom of what? Also are you certain that the stream you're passing to the decoder contains only raw Lz4 data? If there are any header or other bytes it will try to decode those and yield invalid data.

**Comment by Trasiva** [comment]
<code>DownloadCapture</code> is supposed to take the <code>Lz4DecoderStream</code> and check if the final product is supposed to be a compressed file (gzip or zip), if so begin the appropriate wrapper stream. At this point it heads over to a processing function to begin reading the stream (in this case, it's the Lz4DecoderStream).

``` C#
if (input.ReadByte() == 'R' && input.ReadByte() == 'D' && input.ReadByte() == 'C' && input.ReadByte() == 1)
{
    //This is where all the stuff happens at if the buffer had valid data.
}
```

In regards to my items being at the "bottom" the <code>Lz4DecoderStream</code>, what I mean is if you look at the buffer, it looks like this:

``` C#
    [0] 0
    ...
    [65535] 0
    [65536] 82 //First actual value, hex for "R"
```

At this point I get another 127 additional bytes which are valid data, totalling the <code>Lz4DecoderStream</code> buffer size of 65664. Due to the way that the DecoderStream is set up, it doesn't allow me to utilize stream.length in order to start at the end of the buffer.

It's important to note that since from **my** understanding of your code, the <code>Lz4DecoderStream</code> data must start after the Lz4 header information, which you'll note is the case, with the previously displayed code.

``` C#
//Set the stream postion at the end of the header position to 'R'.
int intRead = st.Read(buffer, 0, 13);
//Check if we have the magic number. Currently the value (in little endian) is 0x184D2204
 if (buffer[3] == 0x18 && buffer[2] == 0x4D && buffer[1] == 0x22 && buffer[0] == 0x04)
{
}
```

Hopefully I explained it better, if not I can certainly see about clarifying. I've been beating my head against this for about three days at this point.

**Comment by pdjonov** [comment]
OK, so you _are_ looking at the buffer inside of `Lz4DecodeStream`. Sorry, I got a bit confused. What you're seeing is indeed correct with respect to how the decoder works.

The buffer is divided into two sections. The first 64K is a circular buffer containing a copy of the last bunch of _uncompressed_ data. The next bit is a 128-byte (as configured by `InBufLen`) buffer containing _compressed_ data. This part of the buffer is filled from the input stream, and it exists so that we don't do a `Read` call for every single byte of data (since the underlying Lz4 algorithm consumes data one byte at a time).

The idea is, when you call `Read` on the stream, it will call `Read` on the underlying stream to refill the `InBufLen` part of its buffer. It will then decode from there into the output, after which it's going to add the newly decoded data to the circular buffer (the 64K part).

And yes, you just feed it raw Lz4 data, so I think you've got that right.

So, I'm not entirely sure what the bug is... If it's giving invalid output, then could you send me data for a repro case? I'd need the raw Lz4 bytes that it can't decode correctly and the bytes you expect them to decode to.

**Comment by Trasiva** [comment]
I can do that, would it be possible to send you the data via email? I'd rather not have this data just floating around on Git.

**Comment by pdjonov** [comment]
If you've pulled down the repo, you should see my email address in the commit logs.
